---
- hosts: servers
  gather_facts: False
  connection: local
  tasks:
  - name: Create Policy Group for VPCs
    cisco.aci.aci_interface_policy_leaf_policy_group:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      certificate_name: admin
      private_key: "{{ lookup('file', 'certs/admin.key') }}"
      validate_certs: no
      lag_type: node
      policy_group: '{{ ansible_host }}'
      link_level_policy: 10G_Auto
      cdp_policy: CDP_Enabled
      lldp_policy: LLDP_Enabled
      port_channel_policy: LACP_Enabled
      aep: Servers_AAEP
      state: present