---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Ensure we have a certificate installed
    cisco.aci.aci_aaa_user_certificate:
      validate_certs: no
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      aaa_user: admin
      certificate_name: admin
      certificate: "{{ lookup('file', 'certs/admin.crt') }}"